axon:
  eventhandling:
    processors:
      user_read_model:
        mode: subscribing

server:
  error:
    include-stacktrace: never

policy:
  refund-deadline-days: 30
  commission-percentage: 0.1

spring:
  jpa:
    open-in-view: false

stripe:
  seller:
    # Where to send the user if the link expires or they click "refresh"
    refresh-url: http://localhost:3000/api/stripe/callback/refresh
    # Where to send the user after they finish the form (FE "Success" page).
    return-url: http://localhost:3000/api/stripe/callback/return
